/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIStuff;
        
import java.io.File;
import java.util.Calendar;
import java.util.LinkedList;
import javax.swing.JFileChooser;
import mainpckg.Driver;
import mainpckg.Save;

/**
 *
 * @author owenralbovsky
 */
public class DLMainMenu extends javax.swing.JFrame {

    private Driver currentDriver;
    private LinkedList<javax.swing.JTextField> fields = new LinkedList<javax.swing.JTextField>();
    
    /**
     * Creates new form DLMainMenu
     */
    public DLMainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try
        {
            if(currentDriver.equals(null))
            {

            }
        }
        catch(NullPointerException e)
        {
            currentDriver = Driver.drivers.getFirst();
        }
        System.out.println(currentDriver);
        displayPanel = new javax.swing.JPanel();
        driversLoadedLabel = new javax.swing.JLabel();
        driversLenLabel = new javax.swing.JLabel();
        driversLicense = new javax.swing.JPanel();
        dlLabel = new javax.swing.JLabel();
        expLabel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        LNLabel = new javax.swing.JLabel();
        FNLabel1 = new javax.swing.JLabel();
        sexLabel = new javax.swing.JLabel();
        hairLabel = new javax.swing.JLabel();
        HGTLabel = new javax.swing.JLabel();
        eyesLabel = new javax.swing.JLabel();
        WGTLabel = new javax.swing.JLabel();
        stateField = new javax.swing.JTextField();
        dlField = new javax.swing.JTextField();
        organDonorBox = new javax.swing.JCheckBox();
        expDateField = new javax.swing.JTextField();
        dobField = new javax.swing.JTextField();
        lastNameBox = new javax.swing.JTextField();
        firstNameBox = new javax.swing.JTextField();
        sexField = new javax.swing.JTextField();
        hairField = new javax.swing.JTextField();
        heightField = new javax.swing.JTextField();
        weightField = new javax.swing.JTextField();
        eyesField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        cityField = new javax.swing.JTextField();
        stateAddressField = new javax.swing.JTextField();
        postalCodeField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        setBackground(java.awt.Color.pink);
        setBounds(new java.awt.Rectangle(800, 450, 0, 0));

        displayPanel.setBackground(new java.awt.Color(102, 102, 102));

        driversLoadedLabel.setForeground(new java.awt.Color(255, 255, 255));
        driversLoadedLabel.setText("Drivers Loaded: ");

        driversLenLabel.setForeground(new java.awt.Color(204, 255, 255));
        driversLenLabel.setText(Driver.drivers.size() + "");

        driversLicense.setBackground(new java.awt.Color(153, 153, 153));
        driversLicense.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));

        dlLabel.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        dlLabel.setForeground(new java.awt.Color(0, 51, 153));
        dlLabel.setText("DL");

        expLabel.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        expLabel.setForeground(new java.awt.Color(0, 51, 153));
        expLabel.setText("EXP");

        dobLabel.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        dobLabel.setForeground(new java.awt.Color(0, 51, 153));
        dobLabel.setText("DOB");

        LNLabel.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        LNLabel.setForeground(new java.awt.Color(0, 51, 153));
        LNLabel.setText("LN");

        FNLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        FNLabel1.setForeground(new java.awt.Color(0, 51, 153));
        FNLabel1.setText("FN");

        sexLabel.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        sexLabel.setForeground(new java.awt.Color(0, 51, 153));
        sexLabel.setText("SEX");

        hairLabel.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        hairLabel.setForeground(new java.awt.Color(0, 51, 153));
        hairLabel.setText("HAIR");

        HGTLabel.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        HGTLabel.setForeground(new java.awt.Color(0, 51, 153));
        HGTLabel.setText("HGT");

        eyesLabel.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        eyesLabel.setForeground(new java.awt.Color(0, 51, 153));
        eyesLabel.setText("EYES");

        WGTLabel.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        WGTLabel.setForeground(new java.awt.Color(0, 51, 153));
        WGTLabel.setText("WGT");

        stateField.setBackground(null);
        stateField.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        stateField.setForeground(new java.awt.Color(0, 51, 153));
        stateField.setText(currentDriver.getState());
        stateField.setBorder(null);
        stateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateFieldActionPerformed(evt);
            }
        });

        dlField.setBackground(null);
        dlField.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        dlField.setForeground(new java.awt.Color(255, 0, 51));
        dlField.setText(currentDriver.getDLNum() + "");
        dlField.setBorder(null);
        dlField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlFieldActionPerformed(evt);
            }
        });

        organDonorBox.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        organDonorBox.setForeground(new java.awt.Color(255, 204, 204));
        organDonorBox.setText("TODO");

        expDateField.setBackground(null);
        expDateField.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        expDateField.setForeground(new java.awt.Color(255, 0, 51));
        expDateField.setText(currentDriver.toCal(currentDriver.getEXPDate()).get(Calendar.MONTH) + "/" + currentDriver.toCal(currentDriver.getEXPDate()).get(Calendar.DAY_OF_WEEK) + "/" + currentDriver.toCal(currentDriver.getEXPDate()).get(Calendar.YEAR));
        expDateField.setBorder(null);
        expDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expDateFieldActionPerformed(evt);
            }
        });

        dobField.setBackground(null);
        dobField.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        dobField.setForeground(new java.awt.Color(255, 0, 51));
        dobField.setText(currentDriver.toCal(currentDriver.getDOBDate()).get(Calendar.MONTH) + "/" + currentDriver.toCal(currentDriver.getDOBDate()).get(Calendar.DAY_OF_WEEK) + "/" + currentDriver.toCal(currentDriver.getDOBDate()).get(Calendar.YEAR));
        dobField.setBorder(null);
        dobField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobFieldActionPerformed(evt);
            }
        });

        lastNameBox.setBackground(null);
        lastNameBox.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lastNameBox.setText(currentDriver.getLastName());
        lastNameBox.setBorder(null);
        lastNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameBoxActionPerformed(evt);
            }
        });

        firstNameBox.setBackground(null);
        firstNameBox.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        firstNameBox.setText(currentDriver.getFirstName());
        firstNameBox.setBorder(null);
        firstNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameBoxActionPerformed(evt);
            }
        });

        sexField.setBackground(null);
        sexField.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        sexField.setText(currentDriver.getGender());
        sexField.setBorder(null);
        sexField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexFieldActionPerformed(evt);
            }
        });

        hairField.setBackground(null);
        hairField.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        hairField.setText(currentDriver.getEyeColor());
        hairField.setBorder(null);

        heightField.setBackground(null);
        heightField.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        heightField.setText("TODO");
        heightField.setBorder(null);

        weightField.setBackground(null);
        weightField.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        weightField.setText("TODO");
        weightField.setBorder(null);

        eyesField.setBackground(null);
        eyesField.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        eyesField.setText(currentDriver.getEyeColor());
        eyesField.setBorder(null);
        eyesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eyesFieldActionPerformed(evt);
            }
        });

        addressField.setBackground(null);
        addressField.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        addressField.setText(currentDriver.getAddress());
        addressField.setBorder(null);
        addressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFieldActionPerformed(evt);
            }
        });

        cityField.setBackground(null);
        cityField.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        cityField.setText(currentDriver.getCity());
        cityField.setBorder(null);
        cityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityFieldActionPerformed(evt);
            }
        });

        stateAddressField.setBackground(null);
        stateAddressField.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        stateAddressField.setText(currentDriver.getState());
        stateAddressField.setBorder(null);
        stateAddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateAddressFieldActionPerformed(evt);
            }
        });

        postalCodeField.setBackground(null);
        postalCodeField.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        postalCodeField.setText(currentDriver.getPostalCode() + "");
        postalCodeField.setBorder(null);
        postalCodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postalCodeFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout driversLicenseLayout = new javax.swing.GroupLayout(driversLicense);
        driversLicense.setLayout(driversLicenseLayout);
        driversLicenseLayout.setHorizontalGroup(
            driversLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driversLicenseLayout.createSequentialGroup()
                .addGroup(driversLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(driversLicenseLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(driversLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(driversLicenseLayout.createSequentialGroup()
                                .addComponent(LNLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(driversLicenseLayout.createSequentialGroup()
                                .addComponent(FNLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(driversLicenseLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(stateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(driversLicenseLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(organDonorBox))
                    .addGroup(driversLicenseLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(driversLicenseLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 19, Short.MAX_VALUE)
                        .addComponent(stateAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 24, Short.MAX_VALUE)
                        .addComponent(postalCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, driversLicenseLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(driversLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, driversLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(driversLicenseLayout.createSequentialGroup()
                                    .addComponent(dobLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(driversLicenseLayout.createSequentialGroup()
                                    .addComponent(expLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(expDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, driversLicenseLayout.createSequentialGroup()
                                    .addComponent(dlLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(dlField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(9, 9, 9)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, driversLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(driversLicenseLayout.createSequentialGroup()
                                    .addGroup(driversLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(hairLabel)
                                        .addComponent(HGTLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(driversLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(hairField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(heightField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(driversLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(driversLicenseLayout.createSequentialGroup()
                                            .addComponent(WGTLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(weightField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(driversLicenseLayout.createSequentialGroup()
                                            .addComponent(eyesLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(eyesField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(driversLicenseLayout.createSequentialGroup()
                                    .addComponent(sexLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(sexField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        driversLicenseLayout.setVerticalGroup(
            driversLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driversLicenseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(driversLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlLabel)
                    .addComponent(dlField, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(driversLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expLabel)
                    .addComponent(expDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(driversLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobLabel)
                    .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(organDonorBox)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(driversLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNLabel)
                    .addComponent(lastNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(driversLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FNLabel1)
                    .addComponent(firstNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(driversLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postalCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(driversLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexLabel)
                    .addComponent(sexField, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(driversLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hairLabel)
                    .addComponent(eyesLabel)
                    .addComponent(hairField, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eyesField, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(driversLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HGTLabel)
                    .addComponent(WGTLabel)
                    .addComponent(heightField, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightField, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Displaying Driver " + currentDriver.getID());

        jButton2.setForeground(new java.awt.Color(0, 153, 255));
        jButton2.setText("Next Driver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionClick(evt);
            }
        });

        saveButton.setForeground(new java.awt.Color(0, 153, 255));
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(driversLicense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(displayPanelLayout.createSequentialGroup()
                                .addComponent(driversLoadedLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(driversLenLabel)))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(displayPanelLayout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayPanelLayout.createSequentialGroup()
                                .addComponent(saveButton)
                                .addGap(74, 74, 74))))))
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayPanelLayout.createSequentialGroup()
                        .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(driversLoadedLabel)
                            .addComponent(driversLenLabel))
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addComponent(driversLicense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addComponent(saveButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actionClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionClick
            if(currentDriver.getID() == Driver.drivers.size())
            currentDriver = Driver.drivers.get(0);
        else
            currentDriver = Driver.drivers.get(currentDriver.getID());

        stateField.setText(currentDriver.getState());
        dlField.setText(currentDriver.getDLNum() + "");
        expDateField.setText(currentDriver.toCal(currentDriver.getEXPDate()).get(Calendar.MONTH) + "/" + currentDriver.toCal(currentDriver.getEXPDate()).get(Calendar.DAY_OF_MONTH) + "/" + currentDriver.toCal(currentDriver.getEXPDate()).get(Calendar.YEAR));
        dobField.setText(currentDriver.toCal(currentDriver.getDOBDate()).get(Calendar.MONTH) + "/" + currentDriver.toCal(currentDriver.getDOBDate()).get(Calendar.DAY_OF_MONTH) + "/" + currentDriver.toCal(currentDriver.getDOBDate()).get(Calendar.YEAR));
        lastNameBox.setText(currentDriver.getLastName());
        firstNameBox.setText(currentDriver.getFirstName());
        addressField.setText(currentDriver.getAddress());
        cityField.setText(currentDriver.getCity());
        stateAddressField.setText(currentDriver.getState());
        postalCodeField.setText(currentDriver.getPostalCode() + "");
        sexField.setText(currentDriver.getGender());
        hairField.setText(currentDriver.getEyeColor());
        eyesField.setText(currentDriver.getEyeColor());
        jLabel1.setText("Displaying Driver " + currentDriver.getID());
        
        driversLicense.revalidate();
        driversLicense.repaint();
        displayPanel.revalidate();
        displayPanel.repaint();
    
    }//GEN-LAST:event_actionClick

    private void stateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateFieldActionPerformed
        currentDriver.setState(stateField.getText().trim());
        driversLicense.revalidate();
        driversLicense.repaint();
        
    }//GEN-LAST:event_stateFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        int returnval = fc.showSaveDialog(this);
        if(returnval == JFileChooser.APPROVE_OPTION)
            Save.save(fc.getSelectedFile().getAbsolutePath() + ".xlsx");
    }//GEN-LAST:event_saveButtonActionPerformed

    private void dlFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlFieldActionPerformed
        currentDriver.setDLNum(Integer.parseInt(dlField.getText().trim()));
    }//GEN-LAST:event_dlFieldActionPerformed

    private void expDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expDateFieldActionPerformed
        currentDriver.setEXPDate(expDateField.getText());
    }//GEN-LAST:event_expDateFieldActionPerformed

    private void dobFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobFieldActionPerformed
        currentDriver.setDOBDate(dobField.getText().trim());
    }//GEN-LAST:event_dobFieldActionPerformed

    private void lastNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameBoxActionPerformed
        currentDriver.setLastName(lastNameBox.getText().trim());
    }//GEN-LAST:event_lastNameBoxActionPerformed

    private void firstNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameBoxActionPerformed
        currentDriver.setFirstName(firstNameBox.getText().trim());
    }//GEN-LAST:event_firstNameBoxActionPerformed

    private void addressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFieldActionPerformed
        currentDriver.setAddress(addressField.getText().trim());
    }//GEN-LAST:event_addressFieldActionPerformed

    private void cityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityFieldActionPerformed
        currentDriver.setCity(cityField.getText());
    }//GEN-LAST:event_cityFieldActionPerformed

    private void stateAddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateAddressFieldActionPerformed
        currentDriver.setState(stateField.getText().trim());
        driversLicense.revalidate();
        driversLicense.repaint();
    }//GEN-LAST:event_stateAddressFieldActionPerformed

    private void postalCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postalCodeFieldActionPerformed
        currentDriver.setPostalCode(Integer.parseInt(postalCodeField.getText().trim()));
    }//GEN-LAST:event_postalCodeFieldActionPerformed

    private void sexFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexFieldActionPerformed
        currentDriver.setGender(sexField.getText().trim());
    }//GEN-LAST:event_sexFieldActionPerformed

    private void eyesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eyesFieldActionPerformed
        currentDriver.setEyeColor(eyesField.getText().trim());
    }//GEN-LAST:event_eyesFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DLMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DLMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DLMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DLMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DLMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FNLabel1;
    private javax.swing.JLabel HGTLabel;
    private javax.swing.JLabel LNLabel;
    private javax.swing.JLabel WGTLabel;
    private javax.swing.JTextField addressField;
    private javax.swing.JTextField cityField;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JTextField dlField;
    private javax.swing.JLabel dlLabel;
    private javax.swing.JTextField dobField;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JLabel driversLenLabel;
    private javax.swing.JPanel driversLicense;
    private javax.swing.JLabel driversLoadedLabel;
    private javax.swing.JTextField expDateField;
    private javax.swing.JLabel expLabel;
    private javax.swing.JTextField eyesField;
    private javax.swing.JLabel eyesLabel;
    private javax.swing.JTextField firstNameBox;
    private javax.swing.JTextField hairField;
    private javax.swing.JLabel hairLabel;
    private javax.swing.JTextField heightField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lastNameBox;
    private javax.swing.JCheckBox organDonorBox;
    private javax.swing.JTextField postalCodeField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField sexField;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JTextField stateAddressField;
    private javax.swing.JTextField stateField;
    private javax.swing.JTextField weightField;
    // End of variables declaration//GEN-END:variables
}
